apiVersion: v1
kind: Service
metadata:
  namespace: sonarqube
  name: postgres
  labels:
    app: postgres
spec:
  ports:
    - port: 3306
  selector:
    app: postgres
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: sonarqube
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:16.2
        name: postgres
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: sonarqube
              key: db-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sonarqube
              key: db-password
        - name: POSTGRES_DB
          value: sonar      
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: data
        hostPath:
          path: /mnt/webserver/sonarqube/db
 
