apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: sonarqube
  labels:
    app: sonarqube
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  selector:
    app: sonarqube
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: sonarqube
  labels:
    app: sonarqube
spec:
  selector:
    matchLabels:
      app: sonarqube
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - image: sonarqube:9.9.4-community
        name: sonarqube     
        env:
        - name: SONAR_JDBC_USERNAME
          valueFrom:
            secretKeyRef:
              name: sonarqube
              key: db-user
        - name: SONAR_JDBC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sonarqube
              key: db-password
        - name: SONAR_JDBC_URL
          value: jdbc:postgresql://postgres:5432/sonar
        ports:
          - containerPort: 9000
        resources:
          requests:
            memory: "1Gi"  
          limits:
            memory: "4Gi"  
        volumeMounts:
          - name: data
            mountPath: /opt/sonarqube/data
          - name: logs
            mountPath: /opt/sonarqube/logs
          - name: extensions
            mountPath: /opt/sonarqube/extensions
      volumes:
      - name: data
        hostPath:
          path: /mnt/webserver/sonarqube/data
      - name: logs
        hostPath:
          path: /mnt/webserver/sonarqube/logs
      - name: extensions
        hostPath:
          path: /mnt/webserver/sonarqube/extensions   
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarqube
  namespace: sonarqube
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 64m
spec:
  rules:  
  - host: 'sonarqube.marasigan.net'
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: sonarqube
            port:
              number: 80 

